const app=document.getElementById("app");let DB,selected,session=[],level="easy";
let S=JSON.parse(localStorage.getItem("bankHeroV6")||'{"correct":[],"wrong":[],"history":[],"studyDays":[]}');
const save=()=>localStorage.setItem("bankHeroV6",JSON.stringify(S));
const allTopics=()=>DB.subjects.flatMap(s=>s.topics.map(t=>({...t,subject:s.name})));
function touch(){let d=new Date().toISOString().slice(0,10);if(!S.studyDays.includes(d)){S.studyDays.push(d);save()}document.getElementById("streak").textContent="🔥 Study days: "+S.studyDays.length}
fetch("data/content.json",{cache:"no-store"}).then(r=>r.json()).then(x=>{DB=x;touch();home()}).catch(e=>app.innerHTML="<div class='card'><h2>Content loading error</h2><p>Check that data/content.json was uploaded.</p></div>");
function home(){let a=allTopics(),t=a[new Date().getDate()%a.length];let done=S.correct.length,rev=S.wrong.length;app.innerHTML=`<div class="grid"><div class="card"><span class="pill">TODAY'S PRIORITY</span><h2>${t.name}</h2><p>Do this order: learn the idea → study examples → practice → revise mistakes.</p><button class="primary" onclick="openTopic('${t.id}')">Start today's lesson →</button></div><div class="card"><div class="big">${done}</div><p>Questions mastered</p></div><div class="card"><div class="big">${rev}</div><p>Questions to revise</p></div></div><div class="card"><h2>Simple study flow</h2><div class="visual">1️⃣ Learn one concept\n       ↓\n2️⃣ Understand worked examples\n       ↓\n3️⃣ Try Easy → Medium → Hard\n       ↓\n4️⃣ Wrong answer? → Revision\n       ↓\n5️⃣ Review and improve</div></div>`}
function learn(){app.innerHTML="<h2>📚 Learn from Zero</h2><p>Every topic is broken into small concepts. Start with the explanation; shortcuts come later.</p><div id='subjects'></div><div id='topics'></div>";document.getElementById("subjects").innerHTML=DB.subjects.map((s,i)=>`<button class="primary" onclick="showSubject(${i})">${s.name}</button>`).join("");showSubject(0)}
function showSubject(i){let s=DB.subjects[i];document.getElementById("topics").innerHTML="<div class='grid'>"+s.topics.map(t=>`<div class="card topic" onclick="openTopic('${t.id}')"><span class="pill">${s.name}</span><h3>${t.name}</h3><p>${t.concepts.length} concept blocks</p><p class="small">Explain • Visual • Rule • Worked examples • Shortcut • Mistakes</p><button class="primary">Open lesson →</button></div>`).join("")+"</div>"}
function openTopic(id){selected=allTopics().find(t=>t.id===id);touch();app.innerHTML=`<button class="secondary" onclick="learn()">← All topics</button><div class="card"><span class="pill">${selected.subject}</span><h2>📘 ${selected.name}</h2><p>Read each concept slowly. Try to predict the answer before opening the solution.</p>${selected.concepts.map((c,i)=>`<button class="${i===0?"primary":"secondary"}" onclick="showConcept(${i})">${i+1}. ${c.title}</button>`).join("")}</div><div id="lesson"></div><div class="card"><h2>Ready to test yourself?</h2><button class="primary" onclick="startPractice('easy')">🟢 Easy • 30</button><button class="primary" onclick="startPractice('medium')">🟡 Medium • 30</button><button class="primary" onclick="startPractice('hard')">🔴 Hard • 30</button></div>`;showConcept(0)}
function showConcept(i){let c=selected.concepts[i];document.getElementById("lesson").innerHTML=`<article class="card lesson"><span class="pill">CONCEPT ${i+1}</span><h2>${c.title}</h2><h3>🧠 Understand it simply</h3><p>${c.simple}</p><h3>👁 See the flow</h3><div class="visual">${c.visual}</div><h3>📌 Rule / Formula</h3><div class="steps">${c.rule}</div><h3>✏️ Different types of examples</h3>${c.examples.map((e,j)=>`<div class="example ${e.level.toLowerCase()}"><span class="pill">${e.level.toUpperCase()}</span><p class="q">Example ${j+1}: ${e.question}</p><div class="steps">${e.steps.map((x,k)=>`${k+1}. ${x}`).join("\n")}\n\n✅ Answer: ${e.answer}</div></div>`).join("")}<div class="tip"><b>⚡ Exam shortcut / thinking method</b><p>${c.shortcut}</p><b>⚠️ Common mistakes</b><ul>${c.mistakes.map(x=>"<li>"+x+"</li>").join("")}</ul></div></article>`}
function makeQ(t,l,n){let z=(n*31+t.name.length*13)%997,x=20+z%180,y=2+z%28,a,q,e,opts;
if(t.name==="Percentage"){let p=5+z%86;base=100+z%900;a=Math.round(p*base)/100;q=`Find ${p}% of ${base}.`;e=`${p}% means ${p}/100.\n${p}/100 × ${base} = ${a}.`;opts=[a,a+2,a+5,Math.max(0,a-3)]}
else if(t.name==="Average"){let b=10+z%30,c=20+z%30,d=30+z%30;a=(b+c+d)/3;q=`Find the average of ${b}, ${c}, ${d}.`;e=`Sum = ${b+c+d}. Divide by 3 = ${a}.`;opts=[a,a+1,a+2,a-1]}
else if(t.name==="Direction Sense"){let dirs=["North","East","South","West"],d=dirs[z%4],op={North:"South",South:"North",East:"West",West:"East"};a=op[d];q=`What direction is opposite to ${d}?`;e=`Opposite pairs are North–South and East–West.\nTherefore the answer is ${a}.`;opts=[a,d,"North","West"]}
else if(t.name==="Tenses"){a="goes";q="She ___ to work every day.";e=`'Every day' shows a routine. With singular subject 'she', simple present uses 'goes'.`;opts=["go","goes","going","gone"]}
else if(t.name==="Articles"){a=z%2?"an":"a";let word=a==="an"?"honest":"university";q=`Choose the correct article: ___ ${word} person`;e=a==="an"?`'honest' has a vowel sound because h is silent, so use an.`:`'university' begins with the 'you' consonant sound, so use a.`;opts=["a","an","the","no article"]}
else if(t.subject==="English"){a="Read grammar and meaning";q=`What is the safest first step in a ${t.name} question?`;e=`Read the full sentence first. Then identify the grammar rule and check whether the answer makes sense.`;opts=[a,"Guess from one word","Ignore context","Choose longest option"]}
else if(t.subject==="Reasoning"){a="Organize the clues";q=`What is the safest first step in a ${t.name} question?`;e=`Write the clues in a diagram, chain, or table before trying to answer.`;opts=[a,"Guess","Ignore conditions","Choose random option"]}
else {if(l==="easy"){a=x+y;q=`Calculate ${x} + ${y}.`;e=`Add carefully: ${x}+${y}=${a}.`}else if(l==="medium"){a=x*y;q=`Calculate ${x} × ${y}.`;e=`Multiply systematically to get ${a}.`}else{let d=2+z%8;a=Math.round(x*y/d);q=`Calculate ${x} × ${y} ÷ ${d}, rounded to nearest integer.`;e=`First multiply, then divide by ${d}. Rounded result = ${a}.`}opts=[a,a+1,a+3,Math.max(0,a-2)]}
return {id:`${t.id}-${l}-${n}`,q,a:String(a),opts:[...new Set(opts.map(String))],explain:e,topic:t.name,level:l}}
function startPractice(l){level=l;session=Array.from({length:600},(_,i)=>makeQ(selected,l,i+1)).filter(q=>!S.correct.includes(q.id)).slice(0,30);if(!session.length){app.innerHTML="<div class='card'><h2>🎉 No new questions remain in the current generated set.</h2><button class='primary' onclick='revision()'>Go to Revision</button></div>";return}renderQuestion(0)}
function practice(){app.innerHTML="<div class='card'><h2>✏️ Practice</h2><p>Choose a topic from Learn. Then solve 30 Easy, Medium or Hard questions. Correct questions are remembered and wrong/skipped questions go to Revision.</p><button class='primary' onclick='learn()'>Choose a topic →</button></div>"}
function renderQuestion(i){if(i>=session.length){app.innerHTML=`<div class="card"><h2>🎉 Practice complete</h2><p>Good work. Correct answers are marked mastered. Wrong or skipped questions remain in your revision queue.</p><button class="primary" onclick="revision()">🔁 Start revision</button><button class="secondary" onclick="progress()">📊 View progress</button></div>`;return}let q=session[i],o=[...q.opts].sort(()=>Math.random()-.5);window.currentOptions=o;app.innerHTML=`<div class="card"><span class="pill">${q.topic} • ${q.level.toUpperCase()} • ${i+1}/30</span><p class="q">${q.q}</p>${o.map((x,k)=>`<button class="option" onclick="answer(${i},${k})">${String.fromCharCode(65+k)}. ${x}</button>`).join("")}<button class="secondary" onclick="skipQuestion(${i})">I don't know → Move to Revision</button><div id="feedback"></div></div>`}
function answer(i,k){let q=session[i],chosen=String(currentOptions[k]),ok=chosen===q.a;if(ok){if(!S.correct.includes(q.id))S.correct.push(q.id);S.wrong=S.wrong.filter(x=>x!==q.id)}else if(!S.wrong.includes(q.id))S.wrong.push(q.id);S.history.push({id:q.id,ok,date:Date.now()});save();document.getElementById("feedback").innerHTML=`<div class="steps"><b>${ok?"🎉 Correct! Excellent.":"💡 Not this time — here is the easy method."}</b>\n\n${q.explain}\n\n<button class="primary" onclick="renderQuestion(${i+1})">Next question →</button></div>`}
function skipQuestion(i){let q=session[i];if(!S.wrong.includes(q.id))S.wrong.push(q.id);S.history.push({id:q.id,ok:false,date:Date.now()});save();renderQuestion(i+1)}
function revision(){let list=[];for(const t of allTopics())for(const l of ["easy","medium","hard"])for(let i=1;i<=600;i++){let q=makeQ(t,l,i);if(S.wrong.includes(q.id))list.push(q)}if(!list.length){app.innerHTML="<div class='card'><h2>🎉 Revision queue is empty</h2><p>Wrong and skipped questions will appear here automatically.</p></div>";return}session=list.slice(0,30);renderQuestion(0)}
function progress(){let total=S.correct.length+S.wrong.length,acc=total?Math.round(S.correct.length/total*100):0;app.innerHTML=`<h2>📊 Progress</h2><div class="grid"><div class="card"><div class="big">${S.correct.length}</div><p>Mastered</p></div><div class="card"><div class="big">${S.wrong.length}</div><p>Revision queue</p></div><div class="card"><div class="big">${acc}%</div><p>Current accuracy</p></div><div class="card"><div class="big">${S.studyDays.length}</div><p>Study days</p></div></div><div class="card"><h3>Accuracy</h3><div class="bar"><i style="width:${acc}%"></i></div><p class="small">The goal is not to get everything correct immediately. Learn → make mistakes → revise → improve.</p></div>`}
function papers(){app.innerHTML=`<div class="card"><h2>📄 Previous Year Papers</h2><p>This section is prepared for adding official/licensed question-paper PDFs and solutions directly into the app.</p><div class="tip"><b>Important:</b> I have not bundled unofficial copies of five years of copyrighted exam papers into this package. Use this area for papers you have permission to upload or official public releases.</div><h3>Recommended organisation</h3><div class="steps">SBI Clerk / Junior Associate\n├── 2021\n├── 2022\n├── 2023\n├── 2024\n└── 2025\n\nIOB LBO\n├── Available official / authorised papers\n└── Topic-wise solution notes</div></div>`}
Object.assign(window,{home,learn,showSubject,openTopic,showConcept,startPractice,practice,renderQuestion,answer,skipQuestion,revision,progress,papers});