const store=JSON.parse(localStorage.getItem('bzh2')||'{"seen":[],"wrong":[],"scores":{}}');const save=()=>localStorage.setItem('bzh2',JSON.stringify(store));let content={},current=[];
fetch('data/content.json').then(r=>r.json()).then(d=>{content=d;go('home')});
const qBank=[
['simplification','easy','8 + 4 × 3',20,'First multiply: 4 × 3 = 12. Then add: 8 + 12 = 20.'],
['simplification','medium','24 ÷ 6 + 7 × 2',18,'Division and multiplication first: 24 ÷ 6 = 4; 7 × 2 = 14; then 4 + 14 = 18.'],
['simplification','hard','(18 + 6) ÷ 3 × 4',32,'Bracket first: 18 + 6 = 24. Then 24 ÷ 3 = 8. Finally 8 × 4 = 32.'],
['inequality','easy','If A > B and B > C, which is true?', 'A > C','Follow the chain: A is greater than B and B is greater than C, so A > C.'],
['inequality','medium','If P ≤ Q and Q < R, which is definitely true?', 'P < R','P can be equal to Q or less than Q; Q is less than R. In both cases P < R.'],
['parts','easy','Identify the verb: "She studies daily."', 'studies','A verb tells us the action or state. Here, "studies" is the action.'],
['parts','medium','Identify the pronoun: "They went to the bank."', 'They','A pronoun replaces a noun. "They" refers to people without naming them.']
];
function layout(html){app.innerHTML='<div class="wrap">'+html+'</div>'}
function go(page){if(!content.topics)return; if(page==='home')home();if(page==='learn')learn();if(page==='practice')practice();if(page==='test')test();if(page==='papers')papers();if(page==='progress')progress()}
function home(){let n=new Date().getDate()%content.topics.length,t=content.topics[n],seen=store.seen.length;layout(`<div class="grid"><div class="card"><span class="pill">TODAY'S PRIORITY</span><h2>${t.subject}: ${t.name}</h2><p>${t.concept}</p><button class="primary" onclick="go('learn')">Start Learning →</button></div><div class="card"><div class="muted">Questions attempted</div><div class="big">${seen}</div><div class="muted">Wrong answers are automatically saved for revision.</div></div><div class="card"><span class="pill">DAILY FLOW</span><p>Learn → Example → Practice → Test → Review mistakes</p></div></div>`)}
function learn(){layout(`<h2>📚 Learn from Zero</h2><div class="grid">${content.topics.map(t=>`<div class="card"><span class="pill">${t.subject}</span><h3>${t.name}</h3><p>${t.concept}</p><div class="solution">${t.visual}</div><button class="primary" onclick="startTopic('${t.id}')">Practice this topic</button></div>`).join('')}</div>`)}
function startTopic(id){current=qBank.filter(q=>q[0]===id);renderQuestion(0)}
function practice(){layout(`<h2>✏️ Daily Practice</h2><p class="muted">Choose a difficulty. The app avoids questions already completed when enough questions exist.</p><div class="grid">${['easy','medium','hard'].map(x=>`<div class="card"><h2>${x==='easy'?'🟢':x==='medium'?'🟡':'🔴'} ${x.toUpperCase()}</h2><p>Learn carefully and read every solution.</p><button class="primary" onclick="startLevel('${x}')">Start</button></div>`).join('')}<div class="card"><h2>🔁 Revision</h2><p>Retry questions you answered incorrectly.</p><button class="primary" onclick="revision()">Revise mistakes</button></div></div>`)}
function startLevel(level){current=qBank.filter(q=>q[1]===level);renderQuestion(0)}
function revision(){current=qBank.filter(q=>store.wrong.includes(q[2]));renderQuestion(0)}
function opts(ans){let a=[ans];while(a.length<4){let x=typeof ans==='number'?ans+(a.length*3):['A > B','P < R','studies','They'][a.length-1]||'None';if(!a.includes(x))a.push(x)}return a.sort(()=>Math.random()-.5)}
function renderQuestion(i){if(!current.length){layout('<div class="card"><h2>🎉 No questions here yet</h2><p>More questions can be added to the question bank without changing the app.</p><button class="primary" onclick="go(\\'practice\\')">Back</button></div>');return}let q=current[i];layout(`<div class="card"><span class="pill">QUESTION ${i+1}/${current.length}</span><h2>${q[2]}</h2><div id="opts">${opts(q[3]).map(o=>`<button class="option" onclick="check(${i},${JSON.stringify(o).replace(/"/g,'&quot;')})">${o}</button>`).join('')}</div><div id="result"></div></div>`)}
function check(i,choice){let q=current[i],ok=String(choice)===String(q[3]);store.seen.push(q[2]);if(!ok&&!store.wrong.includes(q[2]))store.wrong.push(q[2]);if(ok)store.wrong=store.wrong.filter(x=>x!==q[2]);save();[...document.querySelectorAll('.option')].forEach(b=>{b.disabled=true;if(String(b.textContent)===String(q[3]))b.classList.add('correct');if(String(b.textContent)===String(choice)&&!ok)b.classList.add('wrong')});result.innerHTML=`<div class="solution"><b>${ok?'✅ Correct!':'❌ Let us understand it'}</b>\n\n${q[4]}\n\n<button class="primary" onclick="renderQuestion(${i+1})">Next →</button></div>`}
function test(){let qs=qBank.slice().sort(()=>Math.random()-.5).slice(0,Math.min(10,qBank.length));current=qs;renderQuestion(0)}
function papers(){layout(`<h2>📄 Previous Year Papers</h2><p class="muted">These are external resources. Open them to view available papers, answers and solutions. Many recent SBI Clerk papers are memory-based rather than official question-paper PDFs.</p><div class="grid">${content.papers.map(p=>`<div class="card paper"><span class="pill">${p.year}</span><h3>${p.title}</h3><p class="tag">Source: ${p.source}</p><a href="${p.url}" target="_blank" rel="noopener"><button class="primary">View papers / solutions →</button></a></div>`).join('')}</div>`)}
function progress(){let total=store.seen.length,wrong=store.wrong.length,accuracy=total?Math.round((total-wrong)/total*100):0;layout(`<h2>📊 Your Progress</h2><div class="grid"><div class="card"><div class="big">${total}</div>Attempted</div><div class="card"><div class="big">${wrong}</div>Need revision</div><div class="card"><div class="big">${accuracy}%</div>Current accuracy estimate</div></div><div class="card" style="margin-top:16px"><h3>Weak-area rule</h3><p>Wrong answers remain in the revision queue until answered correctly.</p><button class="primary" onclick="revision()">Practice mistakes</button></div>`)}