import {load,mark} from '../engine/progress.js';
const app=document.querySelector('#app'); let learnIndex=[],questionIndex=[],paperIndex=[],progress=load(),selectedTopic=null,allQuestions=[];
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function boot(){learnIndex=await (await fetch('content/learn/index.json')).json();questionIndex=await (await fetch('content/questions/index.json')).json();paperIndex=await (await fetch('content/papers/index.json')).json(); home()}
const nav=()=>`<header><h1>🏦 Bank Zero → Hero</h1><p>Content-first, modular learning system</p><nav><button data-a=home>Today</button><button data-a=learn>Learn</button><button data-a=practice>Practice</button><button data-a=revision>Revision</button><button data-a=progress>Progress</button><button data-a=papers>Papers</button></nav></header>`;
function shell(html){app.innerHTML=nav()+`<main>${html}</main>`;document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>window[b.dataset.a]())}
function home(){shell(`<section class=card><span class=pill>START HERE</span><h2>Learn first. Practice second.</h2><p>This build separates teaching content, question banks and application logic. Replacing one does not require rebuilding the others.</p><button class=primary onclick=learn()>Open Learn</button></section><div class=grid><section class=card><h3>Learn modules</h3><b>${learnIndex.length}</b></section><section class=card><h3>Mastered</h3><b>${progress.mastered.length}</b></section><section class=card><h3>Revision</h3><b>${progress.revision.length}</b></section></div>`)}
function learn(){let groups={};learnIndex.forEach(x=>(groups[x.subject]??=[]).push(x));shell(`<h2>📚 Learn</h2><p>Each topic is an independent JSON module. Open any topic.</p>${Object.entries(groups).map(([s,ts])=>`<h3>${s}</h3><div class=grid>${ts.map(t=>`<section class="card topic"><span class=pill>${s}</span><h3>${t.topic}</h3><p>Independent teaching module</p><button class=primary onclick="openLearn('${t.file}','${t.topic}')">Learn →</button></section>`).join('')}</div>`).join('')}`)}
async function openLearn(file,topic){let d=await (await fetch(file)).json();selectedTopic=topic;shell(`<button onclick=learn()>← Topics</button><section class=card><span class=pill>${esc(d.subject)}</span><h2>${esc(d.topic)}</h2><p>Study each subtopic in order. Every section is replaceable without touching the app.</p></section>${d.subtopics.map((x,i)=>`<article class=card lesson><span class=pill>SUBTOPIC ${i+1}</span><h2>${esc(x.title)}</h2><h3>🧠 Start from zero</h3><p>${esc(x.zero)}</p><h3>👁 Visual model</h3><pre>${esc(x.visual)}</pre><h3>📌 Rule</h3><div class=note>${esc(x.rule)}</div><h3>✏️ Worked examples</h3>${x.examples.map((e,n)=>`<section class="example ${e.level.toLowerCase()}"><b>${e.level} example ${n+1}</b><h4>${esc(e.question)}</h4><ol>${e.solution.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><b>Answer: ${esc(e.answer)}</b></section>`).join('')}<section class=note><b>⚡ Shortcut</b><p>${esc(x.shortcut)}</p><b>⚠️ Common traps</b><ul>${(Array.isArray(x.traps)?x.traps:[x.traps]).map(z=>`<li>${esc(z)}</li>`).join('')}</ul></section></article>`).join('')}<section class=card><h2>Practice this topic</h2><button class=primary onclick="loadPractice('${esc(topic)}')">Take available unique questions →</button></section>`)}
async function loadPractice(topic){selectedTopic=topic;let meta=questionIndex.find(x=>x.topic===topic);if(!meta){shell(`<section class=card><h2>No question bank yet for ${esc(topic)}</h2><p>That is intentional: the architecture does not fake thousands of repeated questions. Add or replace only this topic's JSON file.</p></section>`);return}let d=await (await fetch(meta.file)).json();allQuestions=d.questions;practice()}
function practice(){if(!allQuestions.length){shell(`<section class=card><h2>Choose a topic first</h2><button class=primary onclick=learn()>Choose from Learn</button></section>`);return}let available=allQuestions.filter(q=>!progress.mastered.includes(q.id));shell(`<section class=card><h2>✏️ ${esc(selectedTopic)} Practice</h2><p>${available.length} unique unmastered questions currently in this topic's data file.</p><button class=primary onclick="startTest('Easy')">Easy</button><button class=primary onclick="startTest('Medium')">Medium</button><button class=primary onclick="startTest('Hard')">Hard</button><button onclick="startTest('All')">Mixed</button></section>`)}
let queue=[],pos=0;
function startTest(level){queue=allQuestions.filter(q=>(level==='All'||q.level===level)&&!progress.mastered.includes(q.id));pos=0;if(!queue.length){shell(`<section class=card><h2>No unseen questions at this level</h2><p>Add more unique records to <code>content/questions/${slug(selectedTopic)}.json</code>, or revise existing mistakes.</p><button class=primary onclick=practice()>Back</button></section>`);return}showQuestion()}
function showQuestion(){if(pos>=queue.length){practice();return}let q=queue[pos];shell(`<section class=card><span class=pill>${q.level} • ${pos+1}/${queue.length}</span><h2>${esc(q.question)}</h2>${q.options.map((o,i)=>`<button class=option onclick="answer(${i})">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}<div id=feedback></div></section>`)}
function answer(i){let q=queue[pos],picked=q.options[i],ok=picked===q.answer;progress=mark(progress,q.id,ok);document.querySelectorAll('.option').forEach(x=>x.disabled=true);document.querySelector('#feedback').innerHTML=`<section class=note><h3>${ok?'Correct':'Not correct'}</h3><ol>${q.solution.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><b>Answer: ${esc(q.answer)}</b><p>${ok?'Mastered: this question will not appear in normal practice again.':'Added to Revision.'}</p><button class=primary onclick="nextQuestion()">Next</button></section>`}
function nextQuestion(){pos++;showQuestion()}
function revision(){let ids=new Set(progress.revision);let q=allQuestions.filter(x=>ids.has(x.id));if(!q.length){shell(`<section class=card><h2>Revision</h2><p>No revision questions loaded for the currently selected topic. Choose a topic, then wrong answers will be stored here.</p><button class=primary onclick=learn()>Choose topic</button></section>`);return}queue=q;pos=0;showQuestion()}
function progressView(){shell(`<section class=card><h2>📊 Progress</h2><div class=grid><div class=card><h2>${progress.mastered.length}</h2>Mastered unique questions</div><div class=card><h2>${progress.revision.length}</h2>Need revision</div></div><p>Mastered IDs and revision IDs are stored separately from content. You can replace the entire Learn or Question Bank without changing the app architecture.</p></section>`)}
function papers(){shell(`<section class=card><h2>📄 Previous Papers & Sources</h2><p>Open a source below. This app does not copy restricted or copyrighted papers into the project; it links to the official or source page where the paper/resource is made available.</p></section><div class=grid>${paperIndex.map(p=>`<section class=card><span class=pill>${esc(p.exam)} • ${esc(p.year)}</span><h3>${esc(p.title)}</h3><p><b>Stage:</b> ${esc(p.stage)}</p><p>${esc(p.note)}</p><a class=primary href="${esc(p.url)}" target="_blank" rel="noopener">Open paper / source →</a></section>`).join('')}</div><section class=card><h3>Important note</h3><p>SBI’s own Junior Associate page says it does not provide public copies of answer sheets, question papers or right answer keys. Therefore the SBI section links to official recruitment information rather than pretending those PDFs exist on the official site.</p></section>`)}
window.home=home;window.learn=learn;window.openLearn=openLearn;window.loadPractice=loadPractice;window.practice=practice;window.startTest=startTest;window.answer=answer;window.nextQuestion=nextQuestion;window.revision=revision;window.progress=progressView;window.papers=papers;boot().catch(e=>shell(`<section class=card><h2>Load error</h2><pre>${esc(e.message)}</pre></section>`));
